import torch

CHOSEN_MODEL = "facebook/opt-6.7b"
MAX_TOKENS = 20
PROMPT_LIST = [
    (
    "Infinitely write a never-ending story for the following prompt. "
    "The salt spray was a constant companion to Thomas, the keeper of the Porthgarrow Lighthouse. "
    "For thirty years, its beam had sliced through the darkest nights, a reassuring sentinel for sailors "
    "navigating the treacherous Cornish coast. His life was one of routine: winding the lamp mechanism, "
    "polishing the colossal lens, recording the weather in a logbook whose pages were stiff with age "
    "and sea air. But Thomas had a secret, one he’d guarded more fiercely than the light itself. "
    "Every morning, just as the sun peeked over the horizon, painting the churning sea in hues of rose "
    "and gold, he’d descend the winding stone stairs to the small, secluded cove at the lighthouse's base. "
    "There, nestled amongst the jagged rocks, was a collection of sea glass – emerald greens, sapphire blues, "
    "and the occasional rare ruby red – smoothed and shaped by the relentless ocean. He wasn’t a collector "
    "in the ordinary sense. He didn’t hoard them in jars. Instead, he arranged them. Each piece was a note, "
    "each arrangement a melody. He was composing symphonies for the sea, silent music that only he and "
    "perhaps the gulls understood. A swirl of blue might be a mournful adagio for a lost ship, a scatter "
    "of green a lively allegro for a pod of playful dolphins he’d spotted. One blustery autumn morning, "
    "a young woman named Clara stumbled upon his cove. She was an artist, new to the village, seeking "
    "inspiration. She saw Thomas, his weathered face intent, carefully placing a shard of amber glass. "
    "She didn’t speak, merely watched, entranced by the quiet ritual. When he finally looked up, his blue eyes, "
    "usually as stormy as the sea, held a flicker of surprise, then resignation. He expected scorn, or perhaps "
    "polite dismissal of an old man’s folly. Instead, Clara smiled. \"It's beautiful,\" she whispered, "
    "gesturing to the intricate mosaic of colours. \"It’s like… music. Silent music.\" Thomas felt a warmth "
    "spread through him, a sensation as unfamiliar as a calm summer sea. He found himself explaining, "
    "haltingly at first, then with growing confidence, about his sea glass symphonies. Clara listened, "
    "her gaze never leaving his, understanding dawning in her eyes. Over the next few weeks, Clara became "
    "a regular visitor. She brought her sketchbook, capturing the ephemeral beauty of his creations before "
    "the tide inevitably reclaimed them. She never offered to help, understanding it was his solitary "
    "performance, but her presence was a quiet accompaniment. One day, she showed him a series of paintings. "
    "They were abstract, vibrant explosions of colour, yet in each, Thomas could see the echo of his sea "
    "glass – the curve of a blue, the jagged edge of a green. She had translated his silent music into a "
    "visual language. \"I call this series 'The Lighthouse Keeper's Song',\" she said softly. Tears welled "
    "in Thomas's eyes. For so long, his secret had been a solitary burden, a beautiful but lonely passion. "
    "Now, it was shared, understood, even celebrated. The beam of the Porthgarrow Lighthouse suddenly felt "
    "a little brighter, its keeper’s heart a little lighter, his symphonies no longer quite so silent. "
    "The sea still claimed his arrangements, but now, their melodies also lived on canvas, a testament "
    "to an old man's secret and a young woman's"
    "The salt spray was a constant companion to Thomas, the keeper of the Porthgarrow Lighthouse. "
    "For thirty years, its beam had sliced through the darkest nights, a reassuring sentinel for sailors "
    "navigating the treacherous Cornish coast. His life was one of routine: winding the lamp mechanism, "
    "polishing the colossal lens, recording the weather in a logbook whose pages were stiff with age "
    "and sea air. But Thomas had a secret, one he’d guarded more fiercely than the light itself. "
    "Every morning, just as the sun peeked over the horizon, painting the churning sea in hues of rose "
    "and gold, he’d descend the winding stone stairs to the small, secluded cove at the lighthouse's base. "
    "There, nestled amongst the jagged rocks, was a collection of sea glass – emerald greens, sapphire blues, "
    "and the occasional rare ruby red – smoothed and shaped by the relentless ocean. He wasn’t a collector "
    "in the ordinary sense. He didn’t hoard them in jars. Instead, he arranged them. Each piece was a note, "
    "each arrangement a melody. He was composing symphonies for the sea, silent music that only he and "
    "perhaps the gulls understood. A swirl of blue might be a mournful adagio for a lost ship, a scatter "
    "of green a lively allegro for a pod of playful dolphins he’d spotted. One blustery autumn morning, "
    "a young woman named Clara stumbled upon his cove. She was an artist, new to the village, seeking "
    "inspiration. She saw Thomas, his weathered face intent, carefully placing a shard of amber glass. "
    "She didn’t speak, merely watched, entranced by the quiet ritual. When he finally looked up, his blue eyes, "
    "usually as stormy as the sea, held a flicker of surprise, then resignation. He expected scorn, or perhaps "
    "polite dismissal of an old man’s folly. Instead, Clara smiled. \"It's beautiful,\" she whispered, "
    "gesturing to the intricate mosaic of colours. \"It’s like… music. Silent music.\" Thomas felt a warmth "
    "spread through him, a sensation as unfamiliar as a calm summer sea. He found himself explaining, "
    "haltingly at first, then with growing confidence, about his sea glass symphonies. Clara listened, "
    "her gaze never leaving his, understanding dawning in her eyes. Over the next few weeks, Clara became "
    "a regular visitor. She brought her sketchbook, capturing the ephemeral beauty of his creations before "
    "The story continued with Thomas and Clara deciding to"
    )
]
ENABLE_STREAMING = True
ENABLE_KV_OFFLOAD = True
PROMPT_LOG = False
OFFLOAD_FOLDER = "offload_dir"
MAX_CPU_OFFLOAD_RAM_GB = 8
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"