# --- Weight Placement ---
# W_GPU_PERCENT + W_CPU_PERCENT <= 100
W_GPU_PERCENT = 100
W_CPU_PERCENT = 0

# --- KV Cache Placement ---
# CACHE_GPU_PERCENT + CACHE_CPU_PERCENT <= 100
CACHE_GPU_PERCENT = 100
CACHE_CPU_PERCENT = 0

# --- Activations Placement ---
# ACT_GPU_PERCENT + ACT_CPU_PERCENT <= 100
ACT_GPU_PERCENT = 100
ACT_CPU_PERCENT = 0
