cache_path: "/mnt/ssd/flexgen_cache"
pin_weight: True
use_custom: False
num_copy_threads: 1

w_gpu_percent: 100
w_cpu_percent: 0

cache_gpu_percent: 100
cache_cpu_percent: 0

act_gpu_percent: 100
act_cpu_percent: 0